name: Update IntelliJ Version

on:
  pull_request:

jobs:
  bump-intellij-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - name: Update default IntelliJ version
        run: |
          env | sort
          echo "test it" >> build.sbt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          if [[ -n $(git status | grep 'modified') ]]
          then
            git commit -m "updated default IntelliJ version to XXX"
            COMMIT_SHA=$(git rev-parse HEAD)
            git fetch
            git checkout $GITHUB_BASE_REF
            BRANCH_NAME="update_intellij_version_to_XXX"
            git branch $BRANCH_NAME
            git checkout $BRANCH_NAME
            git cherry-pick $COMMIT_SHA
            git push --set-upstream origin $BRANCH_NAME
          fi
      #- name: create PR
      #  uses: peter-evans/create-pull-request@v4
      #  with:
      #    branch: "update_intellij_version_to_XXX"
      #    base: "main"
