name: Update IntelliJ Version

on:
  pull_request:

jobs:
  bump-intellij-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - name: Update default IntelliJ version
        run: |
          echo "test it" >> build.sbt
      - name: create PR
        uses: peter-evans/create-pull-request@v4
        with:
          branch: "update_intellij_version_to_XXX"
          base: "main"
